#!/usr/bin/python3

import sys

ans = 0

for line in sys.stdin:
    #print(line.rstrip())
    line = line.rstrip()
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)

